arb-dir: l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n
nullable-getter: false
synthetic-package: false
untranslated-messages-file: l10n/untranslated.txt

translator:
  # key_file: translator_key
  # service: Google
  targets:
    - es-ES
    - de
    - fr
    - ja
    - tr
    - uk

  prefer-lang-templates:
    fr: es-ES
    de: es-ES
    uk: de

  prefer-service:
    deepL:
      - tr
      - uk
    # Google:
    #   - es-Es
