name: auto_translator
description: A command-line tool to translate ARB files using Google Cloud Translate.
version: 1.0.2
homepage: https://github.com/theLee3/flutter_auto_translator

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.2.0
  http: ^0.13.4
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.1
  mockito: ^5.1.0
  path: ^1.8.3
  test: ^1.17.0
